### ISSUE TITLE
Incorrect URL for Germany region

### ISSUE THREAD

**Issue by kgriffiths** [IBM-Bluemix-Docs/speech-to-text#75]
Hi,

When managing an actual Watson STT resource, the credentials section incorrectly shows the url as [https://gateway-fra.watsonplatform.net/speech-to-text/api](url) (which returns a 403 Forbidden error) for the German region. Also, the Watson STT API Guide displays this incorrect url.

![console](https://user-images.githubusercontent.com/5571766/43928967-01dbb43c-9c01-11e8-9083-b903500130d0.jpg)

![api](https://user-images.githubusercontent.com/5571766/43928957-fa099c9c-9c00-11e8-8fe2-307a7a9844ab.jpg)

These docs  seem to be the only place in IBM Bluemix that correctly show the German region's URL for speech-to-text as [https://stream-fra.watsonplatform.net/speech-to-text/api](url). 

![docs](https://user-images.githubusercontent.com/5571766/43928975-06fa0306-9c01-11e8-9960-b37fbd95c004.jpg)

This seems to be the only place to raise an issue about documentation. Unless there's something I'm misunderstanding in how to interact with STT in the German region?

Here's an example for reference

![bash](https://user-images.githubusercontent.com/5571766/43929331-810ce450-9c02-11e8-8a13-03f514f5005b.jpg)

**Comment by jeffpk62** [comment]
@kgriffiths You're completely correct, Kevin.  This is an unfortunate artifact of how the documentation is generated at this time.  We are aware of the problem and hoping to address it in the near future.  I'm glad you found the additional references that I added.  I will consider further clarifications in the near future.

**Comment by SirSpidey** [comment]
Updated on [stage1.](http://wdc-watson-master.stage1.mybluemix.net/speech-to-text/api/v1/curl.html?curl#service-endpoint) for both STT and TTS.

**Comment by jeffpk62** [comment]
I saw this change, @SirSpidey ; it looks good.  I assume it'll apply to all services?  Just one small comment:  It might be worth showing the URLs in constant-width font so that they stand out a little better.

**Comment by SirSpidey** [comment]
The change applies only to STT and TTS right now (with `stream-`). I think that other services follow the "standard", but let me know if I'm wrong.

**Comment by jeffpk62** [comment]
@SirSpidey I think only speech uses stream.  I was referring to the list of endpoints, which is what I thought was new.  But I think I see what you changed now, so please ignore my comment.  Sorry for the confusion; it's been a tough month.

**Comment by Brianawalker** [comment]
@SirSpidey Hi, has this change gone public? I just attempted to create a new Lite STT instance in Germany and the url still shows gateway-fra.... in the Service Credentials page. Following this issue as I am supporting a client who is awaiting this change.

**Comment by germanattanasio** [comment]
Yes. It's a platform issue. Let me talk to the team

**Comment by germanattanasio** [comment]
We fixed the issue in the platform. New instances will show the right URL

**Comment by Brianawalker** [comment]
Great! thank you for your attention to this issue @germanattanasio @SirSpidey

**Comment by Brianawalker** [comment]
Just curious, will this change only be reflected in newly created instances? Or will it be reflected in the Service Credentials pages of pre-existing instances as well?

**Comment by germanattanasio** [comment]
Only new instances 😞.

**Comment by jeffpk62** [comment]
I.m closing this issue because it has been addressed.
