### ISSUE TITLE
Contradictory note on training progress

### ISSUE THREAD

**Issue by alex-thewsey-ibm** [IBM-Bluemix-Docs/speech-to-text#86]
The note below regarding the `progress` field (as I read it at least) directly contradicts the bullet point above.

> - `training` indicates that the model is being trained. The `progress` field indicates the progress of the training as a percentage complete.
> > **Note**: The `progress` field does not reflect the progress of the training. The field changes from `0` to `100` when training is complete.

I assume the note is correct. Maybe we could just make the bullet point clearer? I'm no copy writer, but perhaps something along the lines of:

> - `training` indicates that the model is being trained. Note the `progress` field does **not** currently reflect the progress of the training, but changes from `0` to `100` when training is complete.

Edit: Typo

**Comment by jeffpk62** [comment]
Hi, Alex,

The Note was written that way for a few reasons.  (1) To call it out for users who may just skim and not see the caveat when it's embedded as part of the bullet text.  (2) To emphasize the temporary nature of the limitation, which should be addressed sometime soon.  (3) To make the definition of the field complete before describing the limitation.

That said, however, your point is well taken.  If you found it confusing, others may as well.  So I'll look into it as soon as I have a chance.  It'll probably wind up somewhere between what it currently says and what you suggest.

Thanks for taking the time to comment!  I appreciate it.
jeff

**Comment by jeffpk62** [comment]
I've updated the descriptions to make things clearer, @alex-thewsey-ibm.  The changes will be live later this morning.  Thanks again for the feedback.
